version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo Copying apps...
      - cp app.py package/lambda_function.py
      - cd package && zip -r ../app.zip .
artifacts:
  files:
    - app.zip
